# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for Shweta AI Desktop Assistant v2.0

import os
from pathlib import Path

ROOT = Path('.')

a = Analysis(
    ['main.py'],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        # UI / Avatar files
        ('assistant/ui/avatar', 'assistant/ui/avatar'),
        ('assistant/ui/avatar/js', 'assistant/ui/avatar/js'),
        ('assistant/ui/*.py', 'assistant/ui'),
        # Wake word model
        ('assistant/skills/wakeword_models', 'assistant/skills/wakeword_models'),
        # Hand gesture model
        ('hand_landmarker.task', '.'),
        # Contacts & data files
        ('contacts.json', '.'),
        # .env template
        ('.env.example', '.'),
        ('requirements.txt', '.'),
        # Activation bundle (generated by make_activation.py)
        ('activation_bundle.json', '.'),
    ],
    hiddenimports=[
        # Core modules
        'assistant', 'assistant.skills', 'assistant.channels',
        'assistant.voice_input', 'assistant.voice_output',
        'assistant.ai_brain', 'assistant.desktop_control',
        'assistant.ui', 'assistant.ui.avatar_window',
        # Skills
        'assistant.skills.browser', 'assistant.skills.system',
        'assistant.skills.apps', 'assistant.skills.weather',
        'assistant.skills.timer', 'assistant.skills.files',
        'assistant.skills.sysinfo', 'assistant.skills.notes',
        'assistant.skills.windows', 'assistant.skills.briefing',
        'assistant.skills.daily_briefing',
        'assistant.skills.whatsapp', 'assistant.skills.vision',
        'assistant.skills.gesture', 'assistant.skills.market',
        'assistant.skills.browser_agent', 'assistant.skills.browser_auto',
        'assistant.skills.multi_browser',
        'assistant.skills.wakeword', 'assistant.skills.spotify',
        'assistant.skills.email_skill', 'assistant.skills.trading',
        'assistant.skills.multilang', 'assistant.skills.learning',
        'assistant.skills.personality', 'assistant.skills.reaction_lines',
        'assistant.channels.telegram_bot',
        # Third-party
        'edge_tts', 'sounddevice', 'soundfile', 'numpy',
        'pyautogui', 'pyperclip', 'pygetwindow',
        'requests', 'groq', 'google.genai',
        'psutil', 'keyboard', 'pyttsx3', 'comtypes',
        'spotipy', 'telegram',
        'playwright', 'playwright.async_api',
        'PyQt5', 'PyQt5.QtWebEngineWidgets',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'scipy', 'pandas', 'jupyter', 'notebook',
              'torch', 'torchaudio', 'torchvision'],  # torch causes crash on Python 3.14 — loads at runtime
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Shweta',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # No console window
    icon=None,      # Add icon.ico path here if you have one
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=['torch*.dll', 'Qt*.dll'],  # Don't compress these
    name='Shweta',
)
